import { useState, type FormEvent } from 'react'
import type { Customer, Equipment as EquipmentType } from '../types'

type Props = { customers: Customer[]; equipment: EquipmentType[]; onAdd: (item: EquipmentType) => void }
export default function Equipment({ customers, equipment, onAdd }: Props) {
  const [query, setQuery] = useState(''); const [showForm, setShowForm] = useState(false)
  const [customerId, setCustomerId] = useState(customers[0]?.id ?? ''); const [type, setType] = useState('Notebook'); const [brand, setBrand] = useState(''); const [model, setModel] = useState(''); const [problemDescription, setProblemDescription] = useState('')
  const visible = equipment.filter(e => `${e.brand} ${e.model} ${e.type}`.toLowerCase().includes(query.toLowerCase()))
  const customerName = (id: string) => customers.find(c => c.id === id)?.name ?? 'Cliente removido'
  function submit(event: FormEvent) { event.preventDefault(); onAdd({ id: `e-${Date.now()}`, customerId, type, brand, model, problemDescription }); setBrand(''); setModel(''); setProblemDescription(''); setShowForm(false) }
  return <section className="panel page-panel"><div className="panel-head"><div><h2>Equipamentos</h2><p className="muted">Inventário dos aparelhos vinculados aos clientes.</p></div><button className="primary" onClick={() => setShowForm(true)}>+ Novo equipamento</button></div><div className="page-toolbar"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar equipamento..." aria-label="Buscar equipamento" /></div><div className="cards-grid">{visible.map(e => <article className="entity-card" key={e.id}><div className="device-icon">▣</div><div><strong>{e.brand} {e.model}</strong><p>{e.type} · {customerName(e.customerId)}</p><small>{e.problemDescription}</small></div></article>)}</div>{showForm && <div className="overlay"><form className="modal" onSubmit={submit}><div className="modal-head"><h2>Novo equipamento</h2><button type="button" className="icon" onClick={() => setShowForm(false)}>×</button></div><label>Cliente<select required value={customerId} onChange={e => setCustomerId(e.target.value)}>{customers.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="form-grid"><label>Tipo<select value={type} onChange={e => setType(e.target.value)}><option>Notebook</option><option>Desktop</option><option>Smartphone</option><option>Console</option><option>Tablet</option></select></label><label>Marca<input required value={brand} onChange={e => setBrand(e.target.value)} /></label></div><label>Modelo<input required value={model} onChange={e => setModel(e.target.value)} /></label><label>Problema relatado<textarea value={problemDescription} onChange={e => setProblemDescription(e.target.value)} rows={3} /></label><button className="primary">Cadastrar equipamento</button></form></div>}</section>
}
