import { useMemo, useState } from 'react'
import type { Customer, Equipment, OrderStatus, ServiceOrder } from '../types'

type Props = { orders: ServiceOrder[]; customers: Customer[]; equipment: Equipment[]; onEdit: (order: ServiceOrder) => void; onDelete: (id: number) => void; onStatus: (id: number, status: OrderStatus) => void }
const statuses: OrderStatus[] = ['Orçamento', 'Em análise', 'Aprovado', 'Em reparo', 'Pronto', 'Entregue']
const money = (n: number) => n.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })
export default function ServiceOrders({ orders, customers, equipment, onEdit, onDelete, onStatus }: Props) {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'Todos' | OrderStatus>('Todos')
  const customerName = (id: string) => customers.find(c => c.id === id)?.name ?? 'Cliente'
  const equipmentName = (id: string) => { const e = equipment.find(item => item.id === id); return e ? `${e.brand} ${e.model}` : 'Equipamento' }
  const visible = useMemo(() => orders.filter(o => { const text = `${customerName(o.customerId)} ${equipmentName(o.equipmentId)} ${o.issue} #${o.id}`.toLowerCase(); return (filter === 'Todos' || o.status === filter) && text.includes(query.toLowerCase()) }), [orders, query, filter, customers, equipment])
  return <section className="panel"><div className="panel-head"><div><h2>Ordens de serviço</h2><p className="muted">Controle seus atendimentos e acompanhe cada etapa.</p></div><div className="head-actions"><div className="search"><span>⌕</span><input aria-label="Buscar ordens" value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar cliente, aparelho..." /></div><select aria-label="Filtrar por status" value={filter} onChange={e => setFilter(e.target.value as 'Todos' | OrderStatus)}><option>Todos</option>{statuses.map(s => <option key={s}>{s}</option>)}</select></div></div><div className="table-wrap"><table><thead><tr><th>OS</th><th>Cliente</th><th>Equipamento</th><th>Problema</th><th>Valor</th><th>Status</th><th>Atualizado</th><th>Ações</th></tr></thead><tbody>{visible.map(o => <tr key={o.id}><td className="id">#{o.id}</td><td><strong>{customerName(o.customerId)}</strong></td><td>{equipmentName(o.equipmentId)}</td><td>{o.issue}</td><td>{money(o.estimate)}</td><td><button className={`status status-${o.status.toLowerCase().replace(/ /g, '-')}`} onClick={() => onStatus(o.id, statuses[(statuses.indexOf(o.status) + 1) % statuses.length])} title="Avançar status">{o.status}</button></td><td className="muted">{o.updatedAt}</td><td className="actions"><button className="text-button" onClick={() => onEdit(o)}>Editar</button><button className="icon" onClick={() => onDelete(o.id)} aria-label={`Excluir OS ${o.id}`}>×</button></td></tr>)}{!visible.length && <tr><td colSpan={8} className="empty">Nenhuma ordem encontrada com esses filtros.</td></tr>}</tbody></table></div></section>
}
